name = "유준"
nrc = "some"
birth = "some"
experiecnce = "some"
other_qualifacation = "some"
phone = "some"
photo = "om"
website = "ome"
mail = "mmm"
marrie_status = "Single"
education = "school"
gender = "Female"
father = "some"
address = "some"
