name = "Shin Si Ah"
bio = "graphic designer"
about = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec justo id nisi rhoncus aliquet. Fusce vel justo nec eros malesuada sagittis. Nullam rhoncus, nunc eu bibendum blandit, ipsum mi gravida felis, non cursus nunc enim sit amet nisi."
photo = "file:///home/marco/Downloads/shin_si_ah.jpg"
location = "location"
phone = "+82 123 123 123"
mail = "some@some.com"
website = ""

[experences]
  [experences.experences1]
  title = "job position"
  description = "description of job experence"

  [experences.experences2]
  title = "job position 2"
  description = "description of job experence 2"

[educations]
  [educations.educations1]
  title = "milemora university"
  description = "Business Administration career, in progress."
  [educations.educations2]
  title = "brayershire college"
  description = "2017 - 2021"

[languages]
  [languages.languages1]
  title = "Native korean"
  [languages.languages2]
  title = "Advanced english"

[skills]
  [skills.skills1]
  title = "Art"
