father = "cap"
education = "School"
gender = "Female"
marrie_status = "Single"
nrc = "195184"
birth = "1998"
experiecnce = "my best"
address = "yangon"
other_qualifacation = "test qua"

phone = "+82 123 123 123"
name = "some"
photo = "https://media.kbizoom.com/media/2022/12/09083619/cynthia-2-291222.webp"
mail = "hello@reallygreatsite.com"
