phone = "+82 123 123 123"
name = "some"
photo = "https://media.kbizoom.com/media/2022/12/09083619/cynthia-2-291222.webp"
profile_content = "Business Administration student. I consider my self a responsible and orderly person. I am looking forward for my first work experence."
# website = ""
mail = "hello@reallygreatsite.com"
location = "123 Anywhere St., Any city, State, Country 12345"
bio = "Student"

[educations]
  [educations.educations1]
  title = "milemora university"
  description = "Business Administration career, in progress."
  [educations.educations2]
  title = "brayershire college"
  description = "2017 - 2021"

[languages]
  [languages.languages1]
  title = "Native burmese"
  [languages.languages2]
  title = "Advanced korean"

[computer_skills]
  [computer_skills.computer_skills1]
  title = "Text processor."
  [computer_skills.computer_skills2]
  title = "Spredsheet."
  [computer_skills.computer_skills3]
  title = "Slide presentation."

[experences]
  [experences.experences1]
  title = "velveral foods inc."
  description = "Participation in collections to distribute in low-income schools"
